rate_of_doller=float(input("current rate of 1 doller in Indian rupies"))
print(rate_of_doller)
doller_value=input("enter the doller value to convert in indian rupies")
print(doller_value)
Indian_value_of_doller=(rate_of_doller)*(rate_of_doller)
print("indian value of doller",Indian_value_of_doller)